services:
  client:
    build:
      context: ./client
    ports:
      - "3001:80"  # map Nginx port 80 -> localhost:3001
    depends_on:
      - server
    restart: unless-stopped

  server:
    build:
      context: ./server
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    restart: unless-stopped
